In [1]:
import sys
from lib.restartable_pendulum import RestartablePendulumEnv
from lib import state_rep_torch as srt
import gym
import numpy as np
from matplotlib import pyplot as plt
import torch
from lib import utils
from lib import encoder_wrappers as ew

# specify environment information
n_repeats = 1 # step the environment this many times for each action, concatenate the pixel observations
env = RestartablePendulumEnv(repeats=n_repeats,pixels=False)

for t in range(10):
    obs, rew, done, info = env.step(np.asarray([0.0]))
    print(obs, rew, done, info)
    #env.render()

[ 0.9909521   0.13421597 -0.28143481] -0.03751904041149873 False {}
[ 0.99212474  0.12525375 -0.18077283] -0.026043701712562442 False {}
[ 0.99265919  0.12094515 -0.08683252] -0.019039120785019993 False {}
[0.99263573 0.12113754 0.00387635] -0.01545360347884343 False {}
[0.99205083 0.12583776 0.0947295 ] -0.014748152640962709 False {}
[0.99081666 0.13521223 0.18910783] -0.016816807315905458 False {}
[0.98874813 0.14958991 0.290517  ] -0.02197103701868538 False {}
[0.98553584 0.16946715 0.40270943] -0.0309860866045161 False {}
[0.98070132 0.19551197 0.52980979] -0.045215822694480746 False {}
[0.97352906 0.22856329 0.67644376] -0.06679199825690438 False {}


/home/postdoc/holee/.local/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [2]:
# specify environment information
n_repeats = 3 # step the environment this many times for each action, concatenate the pixel observations
env = RestartablePendulumEnv(repeats=n_repeats,pixels=False)

for t in range(10):
    obs, rew, done, info = env.step(np.asarray([0.0]))
    print(obs, rew, done, info)
    #env.render()

[ 0.97327465 -0.22964421 -0.20603668  0.96875746 -0.24801007 -0.37826984
  0.96137551 -0.27524013 -0.56427739] -0.18425096146913664 False {}
[ 0.95005793 -0.31207359 -0.77070749  0.93318787 -0.35938892 -1.00476268
  0.90841126 -0.41807772 -1.27430437] -0.5058122532691404 False {}
[ 0.87239214 -0.48880666 -1.58786266  0.820538   -0.57159198 -1.95446766
  0.74677088 -0.66508139 -2.38316164] -1.6135955959105925 False {}
[ 0.64352516 -0.76542496 -2.88197268  0.5023313  -0.86467524 -3.4560414
  0.31557773 -0.94889973 -4.10454783] -4.973201597151496 False {}
[ 0.08016818 -0.99678135 -4.81622263 -0.19664618 -0.98047452 -5.56380864
 -0.49070123 -0.87132789 -6.29916453] -14.011885329011308 False {}
[-0.75818654 -0.65203771 -6.95266045 -0.94335855 -0.33177498 -7.44168873
 -0.99892643  0.0463249  -7.69051997] -32.45196827406415 False {}
[-0.90932796  0.41608012 -7.65577629 -0.69934464  0.71478464 -7.3437162
 -0.42059298  0.90724944 -6.80762772] -39.6068714128152 False {}
[-0.12739219  0.99185242 

/home/postdoc/holee/.local/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [3]:
# specify environment information
n_repeats = 1 # step the environment this many times for each action, concatenate the pixel observations
env = RestartablePendulumEnv(repeats=n_repeats,pixels=True)

for t in range(10):
    obs, rew, done, info = env.step(np.asarray([0.0]))
    print(obs.shape, rew, done, info)
    #env.render()
n_repeats = 3 # step the environment this many times for each action, concatenate the pixel observations
env = RestartablePendulumEnv(repeats=n_repeats,pixels=True)

for t in range(10):
    obs, rew, done, info = env.step(np.asarray([0.0]))
    print(obs.shape, rew, done, info)
    #env.render()

(1, 64, 64) -4.570427224802251 False {}
(1, 64, 64) -5.001903867325574 False {}
(1, 64, 64) -5.651458867123816 False {}
(1, 64, 64) -6.506487657949412 False {}
(1, 64, 64) -7.542534893183451 False {}
(1, 64, 64) -8.720850867649053 False {}
(1, 64, 64) -9.989284786970128 False {}
(1, 64, 64) -11.28744260414232 False {}
(1, 64, 64) -10.296689320736583 False {}
(1, 64, 64) -9.112811673025254 False {}
(1, 64, 192) -6.90480511598658 False {}
(1, 64, 192) -16.165647722274315 False {}
(1, 64, 192) -33.07571700567803 False {}
(1, 64, 192) -32.68062540288344 False {}
(1, 64, 192) -16.909932812232018 False {}
(1, 64, 192) -7.400919950409628 False {}
(1, 64, 192) -4.236182227170959 False {}
(1, 64, 192) -6.158923127095955 False {}
(1, 64, 192) -14.307954945773464 False {}
(1, 64, 192) -30.253616955712054 False {}


In [4]:
obs.shape

(1, 64, 192)

In [5]:
a = np.asarray([0,1])
#np.concatenate([a,a],axis=1)
np.vstack([a,a])

array([[0, 1],
       [0, 1]])

In [9]:
# specify environment information
n_repeats = 3 # step the environment this many times for each action, concatenate the pixel observations
env = RestartablePendulumEnv(repeats=n_repeats,pixels=False)

deterministic_args = None 

traj_sampler = srt.SimpleTrajectorySampler(env,
                                     srt.sample_pendulum_action_batch,
                                     srt.sample_pendulum_state_batch_old,
                                     device=torch.device("cpu"),
                                     deterministic=False,
                                     deterministic_args=deterministic_args,
                                          output_rewards=True)

#batch_size, T
traj_sampler.obs_shape
#traj_sampler.trajectories
traj_sampler.get_new_batch(2,10)

/home/postdoc/holee/.local/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


([tensor([[-0.9105, -0.4135,  3.4635, -0.8343, -0.5514,  3.1534, -0.7512, -0.6601,
            2.7399],
          [ 0.2583, -0.9661,  1.7207,  0.3060, -0.9520,  0.9962,  0.3194, -0.9476,
            0.2822]]),
  tensor([[-0.6684, -0.7438,  2.3563, -0.5944, -0.8042,  1.9099, -0.5359, -0.8443,
            1.4183],
          [ 0.2851, -0.9585, -0.7209,  0.2011, -0.9796, -1.7322,  0.0645, -0.9979,
           -2.7593]]),
  tensor([[-0.4992, -0.8665,  0.8575, -0.4870, -0.8734,  0.2800, -0.5002, -0.8659,
           -0.3026],
          [-0.1215, -0.9926, -3.7261, -0.3488, -0.9372, -4.6888, -0.5946, -0.8040,
           -5.6100]]),
  tensor([[-0.5435, -0.8394, -1.0141, -0.6130, -0.7901, -1.7058, -0.7018, -0.7124,
           -2.3605],
          [-0.8057, -0.5924, -6.0013, -0.9485, -0.3167, -6.2339, -1.0000, -0.0093,
           -6.2597]]),
  tensor([[-0.7889, -0.6145, -2.6247, -0.8674, -0.4977, -2.8155, -0.9305, -0.3663,
           -2.9187],
          [-0.9562,  0.2929, -6.1307, -0.8332,  0.5530, 

In [7]:
env.observation_space.shape

(9,)

In [8]:
(1,2,3)[0:2]

(1, 2)

In [5]:
import sys
from lib.restartable_pendulum import RestartablePendulumEnv
from lib import state_rep_torch as srt
import gym
import numpy as np
from matplotlib import pyplot as plt
import torch
from lib import utils
from lib import encoder_wrappers as ew

# specify environment information
n_repeats = 1 # step the environment this many times for each action, concatenate the pixel observations
env = RestartablePendulumEnv(repeats=n_repeats,pixels=False)
env.reset(state = [0,0])

for t in range(10):
    obs, rew, done, info = env.step(np.asarray([0.0]))
    print(obs, rew, done, info)
    #env.render()

[ 1.00000000e+00 -4.59242550e-18 -9.18485099e-17] 0.0 False {}
[ 1.00000000e+00 -1.37772765e-17 -1.83697020e-16] -8.436148777472954e-34 False {}
[ 1.0000000e+00 -2.7554553e-17 -2.7554553e-16] -3.374459510989182e-33 False {}
[ 1.0000000e+00 -4.5924255e-17 -3.6739404e-16] -7.592533899725658e-33 False {}
[ 1.00000000e+00 -6.88863825e-17 -4.59242550e-16] -1.3497838043956727e-32 False {}
[ 1.00000000e+00 -9.64409354e-17 -5.51091060e-16] -2.1090371943682386e-32 False {}
[ 1.00000000e+00 -1.28587914e-16 -6.42939570e-16] -3.0370135598902647e-32 False {}
[ 1.00000000e+00 -1.65327318e-16 -7.34788079e-16] -4.133712900961749e-32 False {}
[ 1.00000000e+00 -2.06659147e-16 -8.26636589e-16] -5.399135217582693e-32 False {}
[ 1.00000000e+00 -2.52583402e-16 -9.18485099e-16] -6.833280509753097e-32 False {}
